apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: hackathon-aks
  labels:
    app: simple-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: simple-app