trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  jobs:
  - job: 'Build_Image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerRegistry'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerRegistry'
        repository: 'wortellhackaton/simple-app'
        command: 'buildAndPush'
        Dockerfile: './simple-app/simple-app/Dockerfile'
        tags: 'latest'